### ISSUE TITLE
Crash in iOS due to others plugins not being registered for the background isolate

### ISSUE THREAD

**Issue by Henry-Keys** [nextbss/flutter-push-notification#18]
onMessageReceived callback throws a MissingPluginException. This is probably due to the other plugins not being registered in the background isolate.

```
MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
<asynchronous suspension>
#1      invokeMethod (package:sqflite/src/sqflite_impl.dart:18:34)
<asynchronous suspension>
#2      SqfliteDatabaseFactoryImpl.invokeMethod (package:sqflite/src/factory_impl.dart:33:7)
#3      _SqfliteDatabaseFactoryImpl&Object&SqfliteDatabaseFactoryMixin.safeInvokeMethod.<anonymous closure> (package:sqflite/src/factory_mixin.dart:22:35)
#4      wrapDatabaseException (package:sqflite/src/exception_impl.dart:7:34)
<asynchronous suspension>
#5      SqfliteDatabaseFactoryImpl.wrapDatabaseException (package:sqflite/src/factory_impl.dart:29:7)
#6      _SqfliteDatabaseFactoryImpl&Object&SqfliteDatabaseFactoryMixin.safeInvokeMethod (package:sqflite/src/factory_mixin.dart:22:7)
#7      _SqfliteDatabaseFactoryImpl&Object&SqfliteDatabaseFactoryMixin.getDatabasesPath (package:sqflite/src/factory_mixin.dart:136:17)
<asynchronous suspension>
#8      getDatabasesPath (package:sqflite/sqflite.dart:166:54)
#9      _SqfliteDelegate.open (package:moor_flutter/moor_flutter.dart:55:33)
<asynchronous suspension>
#10     DelegatedDatabase.ensureOpen.<anonymous closure> (package:moor/src/runtime/executor/helpers/engines.dart:251:22)
<asynchronous suspension>
#11     BasicLock.synchronized (package:synchronized/src/basic_lock.dart:31:26)
<asynchronous suspension>
#12     DelegatedDatabase.ensureOpen (package:moor/src/runtime/executor/helpers/engines.dart:245:25)
#13     QueryExecutor.doWhenOpened (package:moor/src/runtime/executor/executor.dart:26:12)
#14     SimpleSelectStatement._getWithQuery (package:moor/src/runtime/statements/select.dart:191:40)
<asynchronous suspension>
#15     SimpleSelectStatement.get (package:moor/src/runtime/statements/select.dart:187:12)
<asynchronous suspension>
#16     SessionInfosDao.getSingle (package:box/data/database/daos/session_infos_dao.dart:27:57)
<asynchronous suspension>
#17     UserSessionPreferences.getSessionInfo (package:box/data/preferences/user_session_preferences.dart:63:30)
<asynchronous suspension>
#18     PushNotificationBackgroundHandler.handlePushNotificationData (package:box/data/background/push_notification_background_handler.dart:18:54)
<asynchronous suspension>
#19     callbackDispatcher.<anonymous closure> (package:flutter_push_notification/src/callback_dispatcher.dart:42:15)
<asynchronous suspension>
#20     MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:397:55)
<asynchronous suspension>
#21     MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:365:54)
#22     _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binary_messenger.dart:110:33)
<asynchronous suspension>
#23     _invoke3.<anonymous closure> (dart:ui/hooks.dart:280:15)
#24     _rootRun (dart:async/zone.dart:1124:13)
#25     _CustomZone.run (dart:async/zone.dart:1021:19)
#26     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#27     _invoke3 (dart:ui/hooks.dart:279:10)
#28     _dispatchPlatformMessage (dart:ui/hooks.dart:141:5)
```

**Comment by Henry-Keys** [comment]
Fixed by #20
