### ISSUE TITLE
Crash while Android app receives notification

### ISSUE THREAD

**Issue by luckycreationsindia** [nextbss/flutter-push-notification#32]
Hi,

App is getting crashed with following error when I send notification from firebase console.

```
W/it.easy_billin(15466): Accessing hidden method Landroid/os/WorkSource;->add(I)Z (light greylist, reflection)
W/it.easy_billin(15466): Accessing hidden method Landroid/os/WorkSource;->add(ILjava/lang/String;)Z (light greylist, reflection)
W/it.easy_billin(15466): Accessing hidden method Landroid/os/WorkSource;->size()I (light greylist, reflection)
W/it.easy_billin(15466): Accessing hidden method Landroid/os/WorkSource;->get(I)I (light greylist, reflection)
W/it.easy_billin(15466): Accessing hidden method Landroid/os/WorkSource;->getName(I)Ljava/lang/String; (light greylist, reflection)
D/AndroidRuntime(15466): Shutting down VM
E/AndroidRuntime(15466): FATAL EXCEPTION: main
E/AndroidRuntime(15466): Process: in.lazybit.easy_billing, PID: 15466
E/AndroidRuntime(15466): java.lang.RuntimeException: Unable to create service ao.co.nextbss.flutter_push_notification.FlutterPushNotificationService: java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.Application android.app.Activity.getApplication()' on a null object reference
E/AndroidRuntime(15466): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3544)
E/AndroidRuntime(15466): 	at android.app.ActivityThread.access$1300(ActivityThread.java:199)
E/AndroidRuntime(15466): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1666)
E/AndroidRuntime(15466): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(15466): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(15466): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime(15466): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15466): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(15466): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/AndroidRuntime(15466): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.Application android.app.Activity.getApplication()' on a null object reference
E/AndroidRuntime(15466): 	at com.github.adee42.keyboardvisibility.KeyboardVisibilityPlugin.registerWith(KeyboardVisibilityPlugin.java:107)
E/AndroidRuntime(15466): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:21)
E/AndroidRuntime(15466): 	at in.lazybit.easy_billing.Application.registerWith(Application.kt:18)
E/AndroidRuntime(15466): 	at ao.co.nextbss.flutter_push_notification.FlutterPushNotificationService.onCreate(FlutterPushNotificationService.kt:106)
E/AndroidRuntime(15466): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3532)
E/AndroidRuntime(15466): 	... 8 more
```

**Comment by Henry-Keys** [comment]
Hi @luckycreationsindia, thanks for reporting this.
Could you please provide the payload or parameters you're sending so we can replicate this?
Thanks

**Comment by luckycreationsindia** [comment]
I figured out:

Crash was caused by keyboard_visibility plugin

I just cloned this project and gave local path for **keyboard_visibility**

**Cloned and changed name in pubspec.yaml to keyboard_visibility and project name to keyboard_visibility**:
[flutter_keyboard_visibility](https://github.com/MisterJimson/flutter_keyboard_visibility)

in my project pubspec.yaml added this:

```
   keyboard_visibility:
     path: keyboard_visibility
```

**Comment by Henry-Keys** [comment]
Can you please provide more information on why this is happening?
Let me get if i'm understanding. *flutter_keyboard_visibility*'s plugin name is magically causing the crash?

**Comment by luckycreationsindia** [comment]
> Can you please provide more information on why this is happening?
> Let me get if i'm understanding. _flutter_keyboard_visibility_'s plugin name is magically causing the crash?

Yes. This plugin is causing issue while receiving notification in foreground.

**Comment by AlexJuca** [comment]
@luckycreationsindia Since the crash was caused by another library and not ours this issue will be closed. If any more issues arise please feel free to get back to us.
