### ISSUE TITLE
App crashes on receive notification on Background

### ISSUE THREAD

**Issue by e200** [nextbss/flutter-push-notification#37]
java.lang.RuntimeException: Unable to create service ao.co.nextbss.flutter_push_notification.FlutterPushNotificationService: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference

**Comment by Henry-Keys** [comment]
Hi @e200 

Please paste the entire stacktrace, the device you're using and your Dart's setup code

**Comment by e200** [comment]
```dart
// ...
import 'package:cinemax_app/src/services/notifications.dart';

// ...

class App extends StatefulWidget {
  App({Key key}) : super(key: key);

  @override
  _AppState createState() => _AppState();
}

class _AppState extends State<App> {
  @override
  void initState() {
    super.initState();

    _notificationsService.init();
  }

  // ..

  }
}
```
```dart
import 'package:flutter_push_notification/flutter_push_notification.dart';

class NotificationsService {
  final _flutterPushNotification = FlutterPushNotification();

  void init() {
    _flutterPushNotification.setup(
      onResume: (notification, data) {
        if (notification != null) {
          print('Notification from foreground:');
          print(notification.title);
          print(notification.body);
        }

        data.forEach((key, value) {
          print('Data from foreground:');
          print('Key: \'$key\' Value: \'$value\'');
        });
      },
      onBackgroundMessage: onBackgroundMessage
    );
  }

  static handleMessage(Map<String, dynamic> message) {
    print('notification from background');
    print(message);
  }

  static void onBackgroundMessage(Map<String, dynamic> message) {
      handleMessage(message);

      FlutterPushNotification().finish();
  }
}
```

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="ao.co.app.app">

    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
    <application
        android:name=".Application"
        android:label="app"
        android:icon="@drawable/icon">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- This keeps the window background of the activity showing
                 until Flutter renders its first frame. It can be removed if
                 there is no splash screen (such as the default splash screen
                 defined in @style/LaunchTheme). -->
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>

            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data
                android:scheme="https"
                android:host="app.ao"/>
            </intent-filter>
        </activity>

        <service
            android:name="ao.co.nextbss.flutter_push_notification.FlutterPushNotificationService"
            android:exported="false">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
    </application>

    <uses-permission android:name="android.permission.INTERNET"/>
</manifest>
```

**Comment by e200** [comment]
```dart
// ...
import 'package:app/src/services/notifications.dart';

// ...

class App extends StatefulWidget {
  App({Key key}) : super(key: key);

  @override
  _AppState createState() => _AppState();
}

class _AppState extends State<App> {
  @override
  void initState() {
    super.initState();

    _notificationsService.init();
  }

  // ..

  }
}
```
```dart
import 'package:flutter_push_notification/flutter_push_notification.dart';

class NotificationsService {
  final _flutterPushNotification = FlutterPushNotification();

  void init() {
    _flutterPushNotification.setup(
      onResume: (notification, data) {
        if (notification != null) {
          print('Notification from foreground:');
          print(notification.title);
          print(notification.body);
        }

        data.forEach((key, value) {
          print('Data from foreground:');
          print('Key: \'$key\' Value: \'$value\'');
        });
      },
      onBackgroundMessage: onBackgroundMessage
    );
  }

  static handleMessage(Map<String, dynamic> message) {
    print('notification from background');
    print(message);
  }

  static void onBackgroundMessage(Map<String, dynamic> message) {
      handleMessage(message);

      FlutterPushNotification().finish();
  }
}
```

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="ao.co.app.app">

    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
    <application
        android:name=".Application"
        android:label="app"
        android:icon="@drawable/icon">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- This keeps the window background of the activity showing
                 until Flutter renders its first frame. It can be removed if
                 there is no splash screen (such as the default splash screen
                 defined in @style/LaunchTheme). -->
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>

            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data
                android:scheme="https"
                android:host="app.ao"/>
            </intent-filter>
        </activity>

        <service
            android:name="ao.co.nextbss.flutter_push_notification.FlutterPushNotificationService"
            android:exported="false">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
    </application>

    <uses-permission android:name="android.permission.INTERNET"/>
</manifest>
```

**Comment by e200** [comment]
It is clearly a conflit with another plugin. But this is bad.

**Comment by Henry-Keys** [comment]
@e200 
Can you try removing FlutterYoutubeView from your app to see if this persists.
I'll try to replicate here to see if this occurs too.

Thanks.

**Comment by e200** [comment]
It's stopped, but I'm not receiving any notification

**Comment by e200** [comment]
It has stopped, but I'm not receiving any notification.

I Still investigating...

**Comment by e200** [comment]
Now we have another issue:

```Restarted application in 2.211ms.
I/flutter (18647): Notifications initialized
I/flutter (18647): dgJ030OQVc0:APA91bFp2d0__PmUt7ce8c1eycRLbD6Upm8sr3VZfz3QhuOQoHQY6fqU3QCc_URysiQB9ibpWmjqpEgtDf9TL6iaTio4W2O_w06KWY9NiH-IzLVKwdyBSq7Xc4FZgEmdvI2iXtt5HDEv
V/InputMethodManager(18647): Starting input: tba=android.view.inputmethod.EditorInfo@9388b26 nm : ao.co.app.app_app ic=null
I/InputMethodManager(18647): [IMM] startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(18647): Input channel constructed: fd=107
D/InputTransport(18647): Input channel destroyed: fd=92
D/AndroidRuntime(18647): Shutting down VM
E/AndroidRuntime(18647): FATAL EXCEPTION: main
E/AndroidRuntime(18647): Process: ao.co.app.app_app, PID: 18647
E/AndroidRuntime(18647): java.lang.RuntimeException: Unable to create service ao.co.nextbss.flutter_push_notification.FlutterPushNotificationService: java.lang.IllegalStateException: registrar.activity() must not be null
E/AndroidRuntime(18647): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3491)
E/AndroidRuntime(18647): 	at android.app.ActivityThread.-wrap6(ActivityThread.java)
E/AndroidRuntime(18647): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1721)
E/AndroidRuntime(18647): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(18647): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime(18647): 	at android.app.ActivityThread.main(ActivityThread.java:6682)
E/AndroidRuntime(18647): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(18647): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
E/AndroidRuntime(18647): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
E/AndroidRuntime(18647): Caused by: java.lang.IllegalStateException: registrar.activity() must not be null
E/AndroidRuntime(18647): 	at com.shatsy.pinchzoomimage.PinchZoomImagePlugin$Companion.registerWith(PinchZoomImagePlugin.kt:18)
E/AndroidRuntime(18647): 	at com.shatsy.pinchzoomimage.PinchZoomImagePlugin.registerWith(PinchZoomImagePlugin.kt)
E/AndroidRuntime(18647): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:27)
E/AndroidRuntime(18647): 	at ao.co.app.app_app.Application.registerWith(Application.kt:18)
E/AndroidRuntime(18647): 	at ao.co.nextbss.flutter_push_notification.FlutterPushNotificationService.onCreate(FlutterPushNotificationService.kt:106)
E/AndroidRuntime(18647): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3481)
E/AndroidRuntime(18647): 	... 8 more
```

**Comment by e200** [comment]
We're having trouble with plugins that deals with the UI @Henry-Keys
